version: '3.7'

services:

  #
  # nxa-sc-caas
  #
  nxa-sc-caas:
    image: nxa-sc-caas:latest
    container_name: nxa-sc-caas
    hostname: "nxa-sc-caas"
    build:
      dockerfile: Dockerfile
      target: run
      context: .
    links:
      - "caas-database:caas-database"
    depends_on:
      - caas-database
    networks:
      - caas_net
    ports:
      - 5500:5500
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      API_DB_USER: ${API_DB_USER}
      API_DB_PASS: ${API_DB_PASS}

  #
  # caas-database
  #
  caas-database:
    hostname: "caas-database"
    container_name: "caas-database"
    image: postgres:12
    environment:
      API_DB_USER: ${API_DB_USER}
      API_DB_PASS: ${API_DB_PASS}
      API_DB_DATABASE: ${API_DB_DATABASE}
      APP_DB_TOKENS: ${APP_DB_TOKENS}
      POSTGRES_PASSWORD: ${API_DB_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
    secrets:
      - apitokens
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - caas-database-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - caas_net

  #
  # pgadmin
  #
  pgadmin:
    hostname: "caas-database-pgadmin"
    container_name: caas-database-pgadmin
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin@xdaro.com
        PGADMIN_DEFAULT_PASSWORD: 0e4896a9-c3c1-46de-bb69-48032f00eccc
    ports:
      - 5050:80
    networks:
      - caas_net

networks:
  caas_net:
    external: false

volumes:
  caas-database-data:

secrets:
  apitokens:
    file: ./aws/db_apitokens.txt
