Build_after_merge:
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  stage: build
  tags:
    - docker
    - build
  before_script:
    - echo $HARBOR_USERNAME
    - echo $HARBOR_REGISTRY
    - echo -n $HARBOR_PASSWORD | docker login -u $HARBOR_USERNAME --password-stdin $HARBOR_REGISTRY
  after_script:
    - docker logout $HARBOR_REGISTRY
  script:
    - docker pull $REGISTRY_IMAGE:latest || true
    - >
      docker build -f Dockerfile
      --pull
      --cache-from $REGISTRY_IMAGE:latest
      --tag $REGISTRY_IMAGE:$CI_COMMIT_SHA
      --tag $REGISTRY_IMAGE:latest
      .
    - docker push $REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $REGISTRY_IMAGE:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH != "master"'
      when: never
    - when: always

deploy_after_merge:
  image: ubuntu
  stage: deploy
  needs: [Build_after_merge]
  allow_failure: false
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  - ssh-keyscan $REMOTE_HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  tags:
  - deploy
  script:
  #
  - ssh ubuntu@$REMOTE_HOST "echo -n $HARBOR_PASSWORD | sudo docker login -u $HARBOR_USERNAME --password-stdin $HARBOR_REGISTRY"
  #
  - scp ./aws/* ubuntu@$REMOTE_HOST:~/docker-compose/
  - scp ./db/* ubuntu@$REMOTE_HOST:~/db/
  - ssh ubuntu@$REMOTE_HOST "ls; pwd;"
  - ssh ubuntu@$REMOTE_HOST "cd docker-compose/; sudo docker-compose down || true"
  - ssh ubuntu@$REMOTE_HOST "cd docker-compose/; sudo docker-compose pull"
  - ssh ubuntu@$REMOTE_HOST "cd docker-compose/; sudo docker-compose up --force-recreate -d"
